[project]
name = "mapvec"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "geopandas", "shapely>=2", "numpy", "pandas", "scikit-learn",
  "tensorflow-hub", "pyarrow", "kagglehub"
]

[tool.setuptools]
package-dir = {"" = "src"}